{{- if .Values.rbac.create }}
{{- if .Values.rbac.pspEnabled }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  labels: {{ include "prometheus-process-exporter.labels" . | indent 4 }}
  name: psp-{{ template "prometheus-process-exporter.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-{{ template "prometheus-process-exporter.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "prometheus-process-exporter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
