{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "prometheus-process-exporter.fullname" . }}
  labels:
    chart: {{ template "prometheus-process-exporter.chart" . }}
    app: {{ template "prometheus-process-exporter.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- if .Values.serviceMonitor.labels }}
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - interval: "{{ .Values.serviceMonitor.interval }}"
    honorLabels: true
    port: metrics
    path: /metrics
    scheme: http
  jobLabel: "{{ .Release.Name }}"
  selector:
    matchLabels:
      app: {{ template "prometheus-process-exporter.name" . }}
      release: "{{ .Release.Name }}"
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
