{{- if .Values.rbac.create -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-process-exporter.serviceAccountName" . }}
  labels:
    app: {{ template "prometheus-process-exporter.name" . }}
    chart: {{ template "prometheus-process-exporter.chart" . }}    
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
imagePullSecrets: 
{{ toYaml .Values.imagePullSecrets | indent 2 }}    
{{- end -}}
{{- end -}}